version: '3.7'

services:
  scf-teste-api:
    container_name: scf-teste-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      TZ: 'America/Sao_Paulo'
    volumes:
      - .:/src/app
      - ./node_modules:/src/app/node_modules
